DROP TABLE users IF EXISTS;


CREATE TABLE users (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30)
);

CREATE INDEX users_id ON users (id);

-- DROP TABLE vet_specialties IF EXISTS;
-- DROP TABLE vets IF EXISTS;
-- DROP TABLE specialties IF EXISTS;
-- DROP TABLE visits IF EXISTS;
-- DROP TABLE pets IF EXISTS;
-- DROP TABLE types IF EXISTS;
-- DROP TABLE owners IF EXISTS;
--
--
-- CREATE TABLE vets (
--                       id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                       first_name VARCHAR(30),
--                       last_name  VARCHAR(30)
-- );
-- CREATE INDEX vets_last_name ON vets (last_name);